[package]
name = "fenix"
version = "0.1.0"
authors = ["José Miguel Sánchez García <jmi2k@openmailbox.org>"]
license = "MIT"

[dependencies]
bitflags = "0.8"
bit = "0.1"
rlibc = "1.0"
spin = "0.4"

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
