[package]
name = "arch_i686"
version = "0.1.0"
authors = ["José Miguel Sánchez García <jmi2k@openmailbox.org>"]

[dependencies]
bitflags = "0.8"

[dependencies.common]
path = "../../common"

[dependencies.multiboot2]
git = "https://github.com/jmi2k/multiboot2-elf64"
branch = "wip"
